#! /bin/bash

python3 -m venv .
source bin/activate
pip install --upgrade pip
pip install numpy scipy scikit-learn matplotlib jupyterlab ipython python-mnist
./bin/emnist_get_data.sh
chmod 755 svm.py
